---
# Homepage configuration

title: "Dashboard"
subtitle: "free-bots"
logo: "YOUR ICON"

header: true
footer: false

columns: "4" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

stylesheet:
  - "assets/custom.css"

theme: default
colors:
  light:
    highlight-primary: "#282a36"
    highlight-secondary: "#bd93f9"
    highlight-hover: "#9473c3"
    background: "#282a36"
    card-background: "#44475a"
    text: "#f8f8f2"
    text-header: "#f8f8f2"
    text-title: "#f8f8f2"
    text-subtitle: "#f8f8f2"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
  dark:
    highlight-primary: "#282a36"
    highlight-secondary: "#bd93f9"
    highlight-hover: "#9473c3"
    background: "#282a36"
    card-background: "#44475a"
    text: "#f8f8f2"
    text-header: "#f8f8f2"
    text-title: "#f8f8f2"
    text-subtitle: "#f8f8f2"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# your configuration: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md
